import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        base: "var(--bg-base)",
        sunken: "var(--bg-sunken)",
        surface: "var(--bg-surface)",
        "surface-2": "var(--bg-surface-2)",
        elevated: "var(--bg-elevated)",
        overlay: "var(--bg-overlay)",
        hover: "var(--bg-hover)",
        active: "var(--bg-active)",
        inset: "var(--bg-inset)",
        neutral: {
          0: "var(--neutral-0)",
          50: "var(--neutral-50)",
          100: "var(--neutral-100)",
          200: "var(--neutral-200)",
          300: "var(--neutral-300)",
          400: "var(--neutral-400)",
          500: "var(--neutral-500)",
          600: "var(--neutral-600)",
          700: "var(--neutral-700)",
          800: "var(--neutral-800)",
          900: "var(--neutral-900)",
          950: "var(--neutral-950)",
        },
        primary: "var(--text-primary)",
        secondary: "var(--text-secondary)",
        tertiary: "var(--text-tertiary)",
        quaternary: "var(--text-quaternary)",
        "on-accent": "var(--text-on-accent)",
        "on-light": "var(--text-on-light)",
        border: {
          subtle: "var(--border-subtle)",
          DEFAULT: "var(--border-default)",
          strong: "var(--border-strong)",
          focus: "var(--border-focus)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          active: "var(--accent-active)",
          muted: "var(--accent-muted)",
          subtle: "var(--accent-subtle)",
        },
        cream: {
          DEFAULT: "var(--cream)",
          hover: "var(--cream-hover)",
          active: "var(--cream-active)",
        },
        success: "var(--success)",
        warning: "var(--warning)",
        danger: "var(--danger)",
        info: "var(--info)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        display: ["var(--font-display)"],
        mono: ["var(--font-mono)"],
        editorial: ["var(--font-editorial)"],
      },
      fontSize: {
        "display-2xl": "var(--fs-display-2xl)",
        "display-xl": "var(--fs-display-xl)",
        "display-lg": "var(--fs-display-lg)",
        h1: "var(--fs-h1)",
        h2: "var(--fs-h2)",
        h3: "var(--fs-h3)",
        h4: "var(--fs-h4)",
        lg: "var(--fs-lg)",
        body: "var(--fs-body)",
        sm: "var(--fs-sm)",
        xs: "var(--fs-xs)",
        "2xs": "var(--fs-2xs)",
        micro: "var(--fs-micro)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        popover: "var(--shadow-popover)",
        modal: "var(--shadow-modal)",
        "highlight-top": "var(--highlight-top)",
      },
      spacing: {
        gutter: "var(--gutter)",
        "gutter-tight": "var(--gutter-tight)",
        "page-x": "var(--page-pad-x)",
        "page-x-sm": "var(--page-pad-x-sm)",
      },
      maxWidth: {
        content: "var(--content-max)",
        wide: "var(--content-wide)",
      },
      transitionDuration: {
        instant: "60ms",
        fast: "120ms",
        base: "180ms",
        slow: "260ms",
        slower: "400ms",
      },
      transitionTimingFunction: {
        out: "cubic-bezier(0.22, 1, 0.36, 1)",
        "in-out": "cubic-bezier(0.65, 0, 0.35, 1)",
        standard: "cubic-bezier(0.4, 0, 0.2, 1)",
        emphasis: "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
